spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.203.146:8848
      config:
        server-addr: 192.168.203.146:8848
        namespace: 95967068-7e71-4c68-b730-f3bea612c9a6
    gateway:
      routes:
        - id: test1
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: test2
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

  application:
    name: mall-gateway

  config:
    import:
      - nacos:mall-gateway.yml?refresh=true&group=dev