spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.203.146:8848
      config:
        server-addr: 192.168.203.146:8848
        namespace: 5a7f052a-1ff0-430d-88a8-0ba45e95c93b

  application:
    name: mall-third-party

  config:
    import:
      - nacos:all.yml?refresh=true&group=dev